# File auto-generated by command: ./bin/make-example main eks tempo v2.1.1

module "tempo" {
  source = "git@github.com:getupcloud/getup-modules//modules/eks/tempo?ref=v2.1.1"

  tempo_cluster_oidc_issuer_url = module.eks.eks_cluster_oidc_issuer_url
  tempo_tags                    = var.tempo_tags
  tempo_retention_days          = var.tempo_retention_days
}
