TERRAFORM ?= terraform

.ONESHELL:

test: fmt lint init validate

fmt:
	$(TERRAFORM) fmt

lint:
	@if type tflint &>/dev/null; then
		tflint
	else
		echo "Ignoring not found: tflint"
	fi

init:
	$(TERRAFORM) init

validate:
	$(TERRAFORM) validate

clean:
	rm -rf .terraform

