# File auto-generated by ./bin/make-example-main for $eks cluster

module "ecr-credentials-sync" {
  source = "git@github.com:getupcloud/getup-modules//modules/eks/ecr-credentials-sync?ref=v1.1.4"

  ecr_credentials_sync_cluster_oidc_issuer_url = module.eks.cluster_oidc_issuer_url
  ecr_credentials_sync_tags                    = var.ecr_credentials_sync_tags
}
