# File auto-generated by command: ./bin/make-example main eks ecr-credentials-sync v2.1.6

module "ecr-credentials-sync" {
  source = "git@github.com:getupcloud/getup-modules//modules/eks/ecr-credentials-sync?ref=v2.1.6"

  ecr_credentials_sync_cluster_oidc_issuer_url = module.eks.eks_cluster_oidc_issuer_url
  ecr_credentials_sync_tags                    = var.ecr_credentials_sync_tags
}
