# File auto-generated by command: ./bin/make-example main eks argocd v2.0.11

module "argocd" {
  source = "git@github.com:getupcloud/getup-modules//modules/eks/argocd?ref=v2.0.11"

  argocd_repository = var.argocd_repository
  argocd_version    = var.argocd_version
  argocd_namespace  = var.argocd_namespace
  argocd_values     = var.argocd_values
  argocd_set        = var.argocd_set
  argocd_set_list   = var.argocd_set_list
}
