# File auto-generated by command: ./bin/make-example main eks external-secrets-operator v2.0.18

module "external-secrets-operator" {
  source = "git@github.com:getupcloud/getup-modules//modules/eks/external-secrets-operator?ref=v2.0.18"

  aws_eso_cluster_oidc_issuer_url = module.eks.eks_cluster_oidc_issuer_url
  aws_eso_namespace               = var.aws_eso_namespace
  aws_eso_service_account         = var.aws_eso_service_account
  aws_eso_aws_region              = module.eks.eks_aws_region
  aws_eso_aws_account_id          = var.aws_eso_aws_account_id
  aws_eso_create_secrets          = var.aws_eso_create_secrets
  aws_eso_secrets                 = var.aws_eso_secrets
  aws_eso_tags                    = var.aws_eso_tags
}
