# File auto-generated by ./bin/make-example-main for $eks cluster

module "cert-manager" {
  source = "git@github.com:getupcloud/getup-modules//modules/eks/cert-manager?ref=v0.23.11"

  cert_manager_cluster_oidc_issuer_url = module.eks.cluster_oidc_issuer_url
  cert_manager_tags                    = var.cert_manager_tags
}
