# File auto-generated by command: ./bin/make-example vars eks cert-manager v2.2.5

## Ignored by config.json:module_mapping_vars
#variable "cert_manager_cluster_oidc_issuer_url" {
#  description = "The URL on the EKS cluster for the OpenID Connect identity provider"
#  type        = string
#}

variable "cert_manager_tags" {
  description = "Tags to apply to all resources."
  type        = any
  default     = {}
}
