# File auto-generated by command: ./bin/make-example main doks loki v2.2.0

module "loki" {
  source = "git@github.com:getupcloud/getup-modules//modules/doks/loki?ref=v2.2.0"

  loki_prefix_path        = var.loki_prefix_path
  loki_bucket_name        = var.loki_bucket_name
  loki_bucket_name_prefix = var.loki_bucket_name_prefix
  loki_bucket_region      = module.doks.doks_region
}
