# File auto-generated by ./bin/make-example-main

module "cert-manager" {
  source = "git@github.com:getupcloud/terraform-modules//modules/cert-manager?ref=v0.23.10"

  cert_manager_cluster_oidc_issuer_url = module.eks.cluster_oidc_issuer_url
  cert_manager_tags                    = var.cert_manager_tags
}
