# File auto-generated by command: ./bin/make-example main eks velero v2.1.1

module "velero" {
  source = "git@github.com:getupcloud/getup-modules//modules/eks/velero?ref=v2.1.1"

  velero_cluster_oidc_issuer_url = module.eks.eks_cluster_oidc_issuer_url
  velero_tags                    = var.velero_tags
  velero_retention_days          = var.velero_retention_days
  velero_retention_prefixes      = var.velero_retention_prefixes
}
