# File auto-generated by command: ./bin/make-example main doks velero v2.0.7

module "velero" {
  source = "git@github.com:getupcloud/getup-modules//modules/doks/velero?ref=v2.0.7"

  velero_prefix_path        = var.velero_prefix_path
  velero_bucket_name        = var.velero_bucket_name
  velero_bucket_name_prefix = var.velero_bucket_name_prefix
  velero_bucket_region      = module.doks.doks_region
}
