# File auto-generated by command: ./bin/make-example main eks opencost v2.0.9

module "opencost" {
  source = "git@github.com:getupcloud/getup-modules//modules/eks/opencost?ref=v2.0.9"

  opencost_cluster_oidc_issuer_url      = module.eks.eks_cluster_oidc_issuer_url
  opencost_namespace                    = var.opencost_namespace
  opencost_service_account              = var.opencost_service_account
  opencost_tags                         = var.opencost_tags
  opencost_cluster_name                 = module.eks.eks_cluster_name
  opencost_create_spot_datafeed_bucket  = var.opencost_create_spot_datafeed_bucket
  opencost_spot_datafeed_bucket_name    = var.opencost_spot_datafeed_bucket_name
  opencost_spot_datafeed_bucket_prefix  = var.opencost_spot_datafeed_bucket_prefix
  opencost_spot_datafeed_retention_days = var.opencost_spot_datafeed_retention_days
}
