# File auto-generated by command: ./bin/make-example main eks vpc_peering v2.0.14

module "vpc_peering" {
  source = "git@github.com:getupcloud/getup-modules//modules/eks/vpc_peering?ref=v2.0.14"

  vpc_peering_owner_vpc_id          = var.vpc_peering_owner_vpc_id
  vpc_peering_owner_route_table_ids = var.vpc_peering_owner_route_table_ids
  vpc_peering_peer_vpc_id           = var.vpc_peering_peer_vpc_id
  vpc_peering_peer_route_table_ids  = var.vpc_peering_peer_route_table_ids
  vpc_peering_tags                  = var.vpc_peering_tags
}
