# File auto-generated by command: ./bin/make-example main eks loki v2.0.15

module "loki" {
  source = "git@github.com:getupcloud/getup-modules//modules/eks/loki?ref=v2.0.15"

  loki_cluster_oidc_issuer_url = module.eks.eks_cluster_oidc_issuer_url
  loki_tags                    = var.loki_tags
  loki_retention_days          = var.loki_retention_days
  loki_retention_prefixes      = var.loki_retention_prefixes
}
