FLAVOR := eks

KUBECONFIG_RETRIEVE_COMMAND = AWS_REGION=$(shell awk '/^aws_region/{print $$3}' *.tfvars 2>/dev/null | tr -d '"') && \
                              aws eks update-kubeconfig --name=$(CLUSTER_NAME) $(AWS_EKS_ARGS) --region $$AWS_REGION

MODULES    := $(shell yq '.modules[]' <modules.yaml)
MODULES_TF := $(patsubst %,main-%.tf variables-%.tf outputs-%.tf terraform-%.auto.tfvars.example,$(MODULES))
