# File auto-generated by command: ./bin/make-example vars eks external-dns v2.1.7

## Ignored by config.json:module_mapping_vars
#variable "external_dns_cluster_oidc_issuer_url" {
#  description = "The URL on the EKS cluster for the OpenID Connect identity provider"
#  type        = string
#}

variable "external_dns_namespace" {
  description = "Namespace for Service Account"
  type        = string
  default     = "external-dns"
}

variable "external_dns_service_account" {
  description = "Service Account name"
  type        = string
  default     = "external-dns"
}

variable "external_dns_aws_region" {
  description = "(Optional) AWS Region where is located External DNS"
  type        = string
  default     = ""
}

variable "external_dns_aws_account_id" {
  description = "(Optional) AWS Account ID where is located External DNS"
  type        = string
  default     = ""
}

variable "external_dns_hosted_zone_ids" {
  description = "(Optional) AWS Account ID where is located External DNS"
  type        = list(string)
  default     = []
}

variable "external_dns_tags" {
  description = "(Optional) Tags to apply to all resources."
  type        = any
  default     = {}
}
