# File auto-generated by command: ./bin/make-example main doks tempo v1.4.1

module "tempo" {
  source = "git@github.com:getupcloud/getup-modules//modules/doks/tempo?ref=v1.4.1"

  tempo_prefix_path        = var.tempo_prefix_path
  tempo_bucket_name        = var.tempo_bucket_name
  tempo_bucket_name_prefix = var.tempo_bucket_name_prefix
  tempo_bucket_region      = module.doks.doks_region
}
