# File auto-generated by command: ./bin/make-example main doks flux v2.0.6

module "flux" {
  source = "git@github.com:getupcloud/getup-modules//modules/doks/flux?ref=v2.0.6"

  flux_doks_region       = module.doks.doks_region
  flux_cluster_name      = module.doks.doks_cluster_name
  flux_github_token      = var.flux_github_token
  flux_github_org        = var.flux_github_org
  flux_github_repository = var.flux_github_repository
  flux_path              = var.flux_path
  flux_version           = var.flux_version
}
